fireking:
  - 2 garunix
  - 3 kirin
  - 3 ponix
  - 3 arvata
  - barong
  - 2 fk_island
  - 2 fk_sanctuary
  - sky_burn
  - tenki
  - original_sinful_spoils
  - one_for_one
  - 3 nadir_servant
  - maximus
  - fleurdelis
  - 3 ash_blossom
  - 3 veiler
  - 3 droll
  - 3 imperm
  - 2 triple_tactics
  - called_by
